In [2]:
import numpy as np

In [3]:
test_array = np.array(["1", "4", 5, 8], float)
test_array

array([1., 4., 5., 8.])

In [4]:
type(test_array[3])

numpy.float64

In [5]:
test_array = np.array([1 ,4 ,5 ,"8"], float)
test_array

array([1., 4., 5., 8.])

In [7]:
type(test_array[3])

numpy.float64

In [8]:
test_array = np.array([1 ,4 ,5 ,"8"], int)
test_array

array([1, 4, 5, 8])

In [9]:
type(test_array[3])

numpy.int64

In [ ]:
test_array = np.array([1 ,4 ,5 ,"8"], str)
test_array

In [12]:
type(test_array[2])

numpy.int64

In [13]:
import copy

In [15]:
a = [[1, 2, 3, 4], [3, 4, 5, 6]]

In [17]:
b = copy.deepcopy(a)

In [18]:
b

[[1, 2, 3, 4], [3, 4, 5, 6]]

In [19]:
b[0][0] = 1000

In [20]:
a

[[1, 2, 3, 4], [3, 4, 5, 6]]

In [21]:
b

[[1000, 2, 3, 4], [3, 4, 5, 6]]

In [25]:
test_array = np.array([1,4,5,"8"], np.float32)
print(test_array)
type(test_array[3])
print(test_array.dtype)
print(test_array.shape)

[1. 4. 5. 8.]
float32
(4,)


In [27]:
test_array = np.array([[1,4,5,"8"]], np.float32)
print(test_array)
print(test_array.dtype)
print(test_array.shape)

[[1. 4. 5. 8.]]
float32
(1, 4)


In [28]:
test_array = np.array([1, 4, 5, "8"], float)
test_array

array([1., 4., 5., 8.])

In [29]:
matrix = [[1,2,5,8], [1,2,5,8],[1,2,5,8]]
np.array(matrix, int).shape

(3, 4)

In [34]:
tensor = [[[1,2,5,8], [1,2,5,8],[1,2,5,8]],
[[1,2,5,8], [1,2,5,8],[1,2,5,8]],
[[1,2,5,8], [1,2,5,8],[1,2,5,8]],
[[1,2,5,8], [1,2,5,8],[1,2,5,8]]]
np.array(tensor, int).shape

(4, 3, 4)

In [35]:
np.array(tensor, int).ndim

3

In [36]:
np.array(tensor, int).size

48

In [37]:
np.array([[1,2,3], [4,5,6]], dtype=int)

array([[1, 2, 3],
       [4, 5, 6]])

In [38]:
np.array([[1,2,3],[4.5,"5","6"]], dtype=np.float32)

array([[1. , 2. , 3. ],
       [4.5, 5. , 6. ]], dtype=float32)